[versions]
wpilib = "2025.3.2"
spotless = "6.20.0"
errorpronePlugin = "4.0.1"
errorprone = "2.28.0"
junit = "5.10.1"
junitPlatform = "1.10.1"

[libraries]
errorprone = { module = "com.google.errorprone:error_prone_annotations", version.ref = "errorprone" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junitPlatform" }

[plugins]
wpilib = { id = "edu.wpi.first.GradleRIO", version.ref = "wpilib" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorpronePlugin" }
